#!/usr/bin/env expect -f
set timeout -1
set pw [exec security find-generic-password -a cphillips -s vpn -w]
spawn /opt/cisco/anyconnect/bin/vpn -s connect {NAME_OF_NETWORK}
expect "Username:"
send -- "cphillips\r"
expect "Password:"
send -- "$pw\r"
expect "Answer:"
expect_user -timeout 3600 -re "(.*)\[\r\n]"
send "$expect_out(1,string)\r"
expect "accept?"
send -- "y\r"
expect eof
