alias showhidden="defaults write com.apple.finder AppleShowAllFiles TRUE && killall Finder"
alias tf="terraform"
alias dv2="source ~/virtualenv/default2.7/bin/activate"
alias dv3="source ~/virtualenv/default3/bin/activate"
alias ans="source ~/virtualenv/ansible/bin/activate"
#alias servethis="python -c 'import SimpleHTTPServer; SimpleHTTPServer.test()'"
alias servethis="python -m SimpleHTTPServer $1"
alias kc="kubectl"
alias lower="python -c '\''import sys; string = sys.argv[1]; string.lower()'"
alias ecr_login="aws ecr get-login --no-include-email --region us-west-2"
alias tfp="terraform plan"
alias tfpl="terraform plan | landscape"
alias tmux_one="/usr/local/bin/tmux attach -t main || tmux new -s main"
alias tmux_two="/usr/local/bin/tmux attach -t second || tmux new -s second"
alias kube_login="~cphillips/k8s-login.py"
alias config="/usr/bin/git --git-dir=${HOME}/.cfg/ --work-tree=${HOME}"
alias g="/usr/bin/git"
